name: MC-Core-Executor
version: 2022.4.1
main: net.verany.api.Core
api-version: 1.18
author: tylix

commands:
  reload:
    aliases: [rl]
  verify:
  afk:
  playtime:
    aliases:
      - pt
  onlinetime:
    aliases:
      - ot
  language:
    aliases:
      - sprache
  credits:
  support:
  globalrank:
    aliases:
      - gr
  chatclear:
